name: Manual operation

on:
  workflow_dispatch:
    inputs:
      flutter_channel:
        default: 'stable'
        required: true
        type: choice
        options:
          - beta
          - master
          - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set Up Java
        uses: actions/setup-java@v6.0.0
        with:
          distribution: "oracle"
          cache: 'gradle'
          java-version: "17"

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.23.0
        with:
          channel: ${{ inputs.flutter_channel }}
          cache: true

      - name: Setup Android SDK Platform 37
        run: |
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "platforms;android-37.1" "build-tools;37.0.0"
          ln -sfn "$ANDROID_HOME/platforms/android-37.1" "$ANDROID_HOME/platforms/android-37"
        shell: bash

      - name: Install Dependencies
        run: flutter pub get
        shell: bash

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor
        shell: bash

      - name: Checking flutter
        run: flutter doctor --verbose
        shell: bash

      - name: Analyze project source
        run: dart analyze
        shell: bash

      - name: Run widget tests
        run: flutter test
        shell: bash

      - name: Build APK
        run: flutter_distributor release --name apk
        shell: bash

      - name: Archive APK
        uses: actions/upload-artifact@v7.0.1
        with:
          name: sms
          path: |
            dist/**
          overwrite: true
          compression-level: 9
